### PR TITLE
Update Definition.xml for new pop up property

### PR DESCRIPTION
**Pull request by PabloSLabbe**

### CODE REVIEW

**Comment by mindspank** [comment]
Looks good, however you need to submit the pull request on my repo and not your fork (copy) of it.

**Comment by mindspank** [comment]
Here is a good help article on Pull Requests which at least I found very useful https://help.github.com/articles/using-pull-requests/

**Comment by PabloSLabbe** [comment]
Hi Alexander, I reviewed the process and tried to edit the code directly in your branch but the system say 'I'm not allowed to write to the file so they automatically fork and tell me to do a pull request'.

**Comment by mindspank** [comment]
No worries, if you want to do you could just email me the files akl(at)qlik.com and I'll merge them on my end.
Sadly I won't be able to tag you as the contributor then,

**Comment by PabloSLabbe** [comment]
No worrie about the contributor tag.  You can mention my name in the code and readme file.
 I will send you the code as soon as I finish some adjustments with text properties.

**Pull request closed without merging**
